jobs:
  include:
    - arch: ppc64le
      dist: bionic
    - arch: ppc64le
      dist: focal
    - arch: ppc64le
      dist: xenial

# arch:
#   - ppc64le

script:
  - cat /etc/os-release
  - uname -m
